### ISSUE TITLE
The problem with route.ts

### ISSUE THREAD

**Issue by peter279k** [lablnet/covid19#23]
As title, looking at the [./web/src/router/route.ts](https://github.com/lablnet/covid19/blob/main/web/src/router/routes.ts#L6) file and it seems that country will always use the `pk` to present the front-end development.

It should have step about adding other countries to let `route.ts` access other routes for that country.

**Comment by lablnet** [comment]
@peter279k Thanks for pointing out,  i will make a fix today.
